/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author alumne
 */
public class IncidenciaCrear extends javax.swing.JFrame {

    /**
     * Creates new form prova
     */
    public IncidenciaCrear() {
        initComponents();
    }

    public JTextField getAssumpteField() {
        return assumpteField;
    }

    public JLabel getAssumpteLabel() {
        return assumpteLabel;
    }

    public JButton getBtnAfegir() {
        return btnAfegir;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextArea getMissatgeField() {
        return missatgeField;
    }

    public JLabel getMissatgeLabel() {
        return missatgeLabel;
    }

    public JComboBox<String> getPrioritatBox() {
        return prioritatBox;
    }

    public JLabel getPrioritatLabel() {
        return prioritatLabel;
    }

    public JLabel getTitolAfegir() {
        return titolAfegir;
    }

    public JButton getBtnTornar() {
        return btnTornar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegir = new javax.swing.JButton();
        assumpteField = new javax.swing.JTextField();
        titolAfegir = new javax.swing.JLabel();
        assumpteLabel = new javax.swing.JLabel();
        missatgeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        missatgeField = new javax.swing.JTextArea();
        prioritatLabel = new javax.swing.JLabel();
        prioritatBox = new javax.swing.JComboBox<>();
        btnTornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAfegir.setText("jButton1");

        assumpteField.setText("jTextField1");

        titolAfegir.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        titolAfegir.setText("jLabel1");

        assumpteLabel.setText("jLabel1");

        missatgeLabel.setText("jLabel1");

        missatgeField.setColumns(20);
        missatgeField.setRows(5);
        jScrollPane1.setViewportView(missatgeField);

        prioritatLabel.setText("jLabel1");

        prioritatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTornar.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTornar)
                        .addGap(142, 142, 142)
                        .addComponent(titolAfegir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assumpteLabel)
                            .addComponent(assumpteField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(missatgeLabel)
                            .addComponent(prioritatLabel)
                            .addComponent(prioritatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titolAfegir)
                    .addComponent(btnTornar))
                .addGap(24, 24, 24)
                .addComponent(assumpteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumpteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(missatgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prioritatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prioritatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnAfegir)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncidenciaCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncidenciaCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncidenciaCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncidenciaCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncidenciaCrear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assumpteField;
    private javax.swing.JLabel assumpteLabel;
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnTornar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea missatgeField;
    private javax.swing.JLabel missatgeLabel;
    private javax.swing.JComboBox<String> prioritatBox;
    private javax.swing.JLabel prioritatLabel;
    private javax.swing.JLabel titolAfegir;
    // End of variables declaration//GEN-END:variables
}
